[phases.setup]
nixPkgs = ["flutter", "python39"]

[phases.install]
cmds = [
  "cd app",
  "flutter pub get",
  "flutter build web",
  "pip install -r requirements.txt"
]

[start]
cmd = "cd app && python server.py" 